name: Run script every 30 mins

on:
  workflow_dispatch:  # Allows manual testing
  schedule:
    - cron: "*/30 * * * *"  # Runs every 30 minutes

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
      run: |
      pip install -r requirements.txt
      pip install selenium  # Ensures Selenium is installed
      - name: Install Chrome & ChromeDriver
      run: |
      sudo apt update
      sudo apt install -y google-chrome-stable
      wget https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip
      unzip chromedriver_linux64.zip
      sudo mv chromedriver /usr/bin/chromedriver



      - name: Run script
        run: python myscript.py
